[package]
name = "engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "engine"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true

[dependencies]
gdnative = "0.9"
